name: create issue

on:
  schedule:
    - cron: "0 0 1 */3 *"

jobs:
  build:
    name: create issue
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issue_template.md
